### ISSUE TITLE
Connecting PN7120S to Phytec AM335X board

### ISSUE THREAD

**Issue by traic** [NXPNFCLinux/linux_libnfc-nci#11]
We have a couple of questions regarding this:

The connector J502 on the Carrier provides access to the I2C bus (I2C0)  of the Phycore module, signals: I2C0_SCL, I2C0_SDA, 3V3 and GND. However, the NXP development kit OM5577/PN7120S (the NFC board has been designed based on this dev kit ) uses two additional lines:
 
1)      IRQ (output, pin D1 on PN7120)  This is the Interrupt request output from radio chip
2)      VEN (input, pin E1 on PN7120) reset pin. Set the device in Hard Power Down

We need to know, from the Software perspective if the signals from the I2C bus are enough to handle the communication with the NFC device, or if any (or both) of the two additional signals (IRQ and VEN) are required.  This has to do with the fact of how the communication between the NFC board and the Phycore SOM is being developed: by constantly polling the devices or if it is interrupt driven.
If the second option is the case, the Carrier board needs to be modified to accommodate two additional GPIO’S from the Phycore Module to the connector J502 in order accomplish these tasks.

**Comment by jgeslin** [comment]
The 2 I2C lines (SDA and SCL) are enough to communicate with PN7120. However, the delivered pn5xx_i2c kernel module assume the handling of VEN (to offers IC reset capabilities to upper SW layers) and IRQ line (to detect whenever PN7120 triggers I2C read request).
If those lines are not connected to host GPIO, the kernel module or upper SW layers must be adpated accordingly.
