### ISSUE TITLE
Build failure buildroot on Ubuntu 18.10 host

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [NXPNFCLinux/linux_libnfc-nci#111]
Hello, we have a problem while building libnfc on ubuntu 18 LTS. We made build script for buildroot and it works on my Manjaro machine, but after transferring to Ubuntu it fails. This is log output produced by buildroot. 

p.s. manual build also doesn't work

>>> libnfc_nci R2.4.1 Configuring
cd /home/ubuntu/buildroot-at91/output/build/libnfc_nci-R2.4.1 && /home/ubuntu/buildroot-at91/output/build/libnfc_nci-R2.4.1/bootstrap
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:11: installing './compile'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
**libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:97: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:140: error: possibly undefined macro: AC_MSG_NOTICE
autoreconf: /usr/bin/autoconf failed with exit status: 1**
(cd /home/ubuntu/buildroot-at91/output/build/libnfc_nci-R2.4.1/ && rm -rf config.cache && PATH="/home/ubuntu/buildroot-at91/output/host/bin:/home/ubuntu/buildroot-at91/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/arm-buildroot-linux-gnueabihf/bin" AR="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ar" AS="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-as" LD="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld" NM="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-nm" CC="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc" GCC="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc" CPP="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-cpp" CXX="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++" FC="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gfortran" F77="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gfortran" RANLIB="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ranlib" READELF="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-readelf" STRIP="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-strip" OBJCOPY="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-objcopy" OBJDUMP="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" LD_FOR_BUILD="/usr/bin/ld" CPPFLAGS_FOR_BUILD="-I/home/ubuntu/buildroot-at91/output/host/include" CFLAGS_FOR_BUILD="-O2 -I/home/ubuntu/buildroot-at91/output/host/include" CXXFLAGS_FOR_BUILD="-O2 -I/home/ubuntu/buildroot-at91/output/host/include" LDFLAGS_FOR_BUILD="-L/home/ubuntu/buildroot-at91/output/host/lib -Wl,-rpath,/home/ubuntu/buildroot-at91/output/host/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-as" DEFAULT_LINKER="/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld" CPPFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  " CXXFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  " LDFLAGS="" FCFLAGS=" -Os " FFLAGS=" -Os " PKG_CONFIG="/home/ubuntu/buildroot-at91/output/host/bin/pkg-config" STAGING_DIR="/home/ubuntu/buildroot-at91/output/host/arm-buildroot-linux-gnueabihf/sysroot" INTLTOOL_PERL=/usr/bin/perl ac_cv_lbl_unaligned_fail=yes ac_cv_func_mmap_fixed_mapped=yes ac_cv_func_memcmp_working=yes ac_cv_have_decl_malloc=yes gl_cv_func_malloc_0_nonnull=yes ac_cv_func_malloc_0_nonnull=yes ac_cv_func_calloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes lt_cv_sys_lib_search_path_spec="" ac_cv_c_bigendian=no   CONFIG_SITE=/dev/null ./configure --target=arm-buildroot-linux-gnueabihf --host=arm-buildroot-linux-gnueabihf --build=x86_64-pc-linux-gnu --prefix=/usr --exec-prefix=/usr --sysconfdir=/etc --localstatedir=/var --program-prefix="" --disable-gtk-doc --disable-gtk-doc-html --disable-doc --disable-docs --disable-documentation --with-xmlto=no --with-fop=no --disable-dependency-tracking --enable-ipv6 --disable-nls --disable-static --enable-shared   )
configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-docs, --disable-documentation, --with-xmlto, --with-fop, --enable-ipv6, --disable-nls
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /home/ubuntu/buildroot-at91/output/build/libnfc_nci-R2.4.1/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for arm-buildroot-linux-gnueabihf-strip... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++... none
checking for arm-buildroot-linux-gnueabihf-gcc... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc
checking whether we are using the GNU C compiler... yes
checking whether /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc accepts -g... yes
checking for /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc option to accept ISO C89... none needed
checking whether /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc understands -c and -o together... yes
checking dependency style of /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc... none
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-buildroot-linux-gnueabihf
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld
checking if the linker (/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-nm
checking the name lister (/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to arm-buildroot-linux-gnueabihf format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld option to reload object files... -r
checking for arm-buildroot-linux-gnueabihf-objdump... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-objdump
checking how to recognize dependent libraries... pass_all
checking for arm-buildroot-linux-gnueabihf-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-buildroot-linux-gnueabihf-ar... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ar
checking for archiver @FILE support... @
checking for arm-buildroot-linux-gnueabihf-strip... (cached) /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-strip
checking for arm-buildroot-linux-gnueabihf-ranlib... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ranlib
checking command to parse /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-nm output from /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for arm-buildroot-linux-gnueabihf-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-cpp
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc supports -fno-rtti -fno-exceptions... no
checking for /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc option to produce PIC... -fPIC -DPIC
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc PIC flag -fPIC -DPIC works... yes
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc static flag -static works... yes
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc supports -c -o file.o... yes
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc supports -c -o file.o... (cached) yes
checking whether the /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-gcc linker (/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ -E
checking for ld used by /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++... /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld
checking if the linker (/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld) is GNU ld... yes
checking whether the /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ linker (/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld) supports shared libraries... yes
checking for /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ option to produce PIC... -fPIC -DPIC
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ PIC flag -fPIC -DPIC works... yes
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ static flag -static works... yes
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ supports -c -o file.o... yes
checking if /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ supports -c -o file.o... (cached) yes
checking whether the /home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-g++ linker (/home/ubuntu/buildroot-at91/output/host/bin/arm-buildroot-linux-gnueabihf-ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int32_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for int16_t... yes
checking for int8_t... yes
checking for ssize_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... (cached) yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for strerror... yes
checking for strstr... yes
checking for clock_gettime... yes
checking for select... yes
checking for dlopen... no
CFLAGS=-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  
CPPFLAGS=-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS=-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  
./configure: line 16664: syntax error near unexpected token `UDEV,'
./configure: line 16664: ` if PKG_CHECK_MODULES(UDEV, libudev,'
package/pkg-generic.mk:228: recipe for target '/home/ubuntu/buildroot-at91/output/build/libnfc_nci-R2.4.1/.stamp_configured' failed
make[1]: *** [/home/ubuntu/buildroot-at91/output/build/libnfc_nci-R2.4.1/.stamp_configured] Error 2
Makefile:84: recipe for target '_all' failed
make: *** [_all] Error 2

**Comment by iprotonotarios** [comment]
You probably need to install pkg-config.

**Comment by ChevalierDeBalibari** [comment]
This is resolved. Some build dependencies like autotools were missing.
