### ISSUE TITLE
problem getting PN7150 into low power mode

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [NXPNFCLinux/linux_libnfc-nci#117]
Hello, 

we have a problem getting PN1750 into low power mode. 

libnfc-nxp-pn547.conf looks like it is already configured for LP mode but if i change any parameter here nothing happens.
libnfc-nxp-init.conf doesn't have enabled detect mode:

NXP_NFC_PROFILE_EXTN={20, 02, 05, 01, A0, 44, 01, 00}

however, if i manually put configuration as provided in AN11697 library fails to load.

**Comment by jgeslin** [comment]
Hi,

Are you refering to the PN7150 standby mode or to the Low power discovery mode (as described in https://www.nxp.com/docs/en/application-note/AN11757.pdf) ?

**Comment by ChevalierDeBalibari** [comment]
Low power discovery mode. We measured pulses on antenna, and they are generated every ~200ms.

**Comment by jgeslin** [comment]
Low power mode discovery for PN7150 is configured thanks to NXP_CORE_CONF_EXTN parameter defined in **libnfc-nxp-pn548.conf** file. Indeed, libnfc-nxp-pn547.conf relates to PN7120 NFC Controller.
Default configuration for PN7150 in NXP_CORE_CONF_EXTN is Low power discovery mode "disabled".
For detailed description of PN7150 Low power discovery mode configuration please refer to https://www.nxp.com/docs/en/application-note/AN11757.pdf.

**Comment by ChevalierDeBalibari** [comment]
Thnaks! I will check it right now!

**Comment by ChevalierDeBalibari** [comment]
Now there isn't any error reported. How can I check that system is working? 

I tried with nfcDemoApp but it doesn't detect tag. Can we do it with it or through libnfc-nci API?

**Comment by jgeslin** [comment]
You can able libnfc-nci traces setting parameters NXPLOG_xxx_LOGLEVEL to 0x03 in libnfc-nxp-init.conf.

**Comment by ChevalierDeBalibari** [comment]
Already did it. Here is the log:

`#########################################################################################
##                                       NFC demo                                      ##
#########################################################################################
##                                 Poll mode activated                                 ##
#########################################################################################
                              ... press enter to quit ...

NxpExtns:   find found NXPLOG_TML_LOGLEVEL=(0x3)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXPLOG_TML_LOGLEVEL=(0x3)

NxpExtns:   find found NXPLOG_FWDNLD_LOGLEVEL=(0x3)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXPLOG_FWDNLD_LOGLEVEL=(0x3)

NxpExtns:   find found NXPLOG_NCIX_LOGLEVEL=(0x3)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXPLOG_NCIX_LOGLEVEL=(0x3)

NxpExtns:   find found NXPLOG_NCIR_LOGLEVEL=(0x3)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXPLOG_NCIR_LOGLEVEL=(0x3)

NxpFunc:    phNxpLog_InitializeLogLevel: global =3, Fwdnld =3, extns =3,                     hal =3, tml =3, ncir =3,                     ncix =3
NxpHal:     Entering phNxpNciHal_init_monitor
NxpHal:     Returning with SUCCESS
NxpExtns:   find found NXP_NFC_DEV_NODE=/dev/pn544

NxpExtns:   GetNxpStrValue: NXP Config Parameter : NXP_NFC_DEV_NODE=/dev/pn544

NxpTml:     phTmlNfc_i2c_open_and_configure

NxpTml:     Opening port=/dev/pn544

NxpTml:     phTmlNfc_i2c_reset(), VEN level 1
NxpFunc:    Nfc: NFC_SetTraceLevel () new_level = 0

NxpTml:     phTmlNfc_i2c_reset(), VEN level 0
NxpTml:     phTmlNfc_i2c_reset(), VEN level 1
NxpTml:     PN54X - Tml Reader Thread Started................

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Tml Writer Thread Started................

NxpTml:     PN54X - Tml Writer Thread Running................

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   4 > 20000101
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     thread started
NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   6 > 400003001101
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   3 > 200100
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =  28 > 40011900031E030008000102038081828302D002FF020004881001A0
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     NxpNci> FW Version: 10.1.a0
NxpHal:     phNxpNciHal_deriveChipType HwVersion : 0x88
NxpHal:     phNxpNciHal_deriveChipType NxpNci > Product : PN548C2
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpExtns:   find found NXP_I2C_FRAGMENTATION_ENABLED=(0x0)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXP_I2C_FRAGMENTATION_ENABLED=(0x0)

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   6 > 20030301A005
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   9 > 4003060001A0050100
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpHal:     i2c_fragmentation_status existing
NxpFwDnld:  Allocating Mem for Dnld Context..
NxpExtns:   GetNxpStrValue: NXP Config Parameter : NXP_NFC_FW_PATH=

NxpFwDnld:  Ignoring Config :NFC FW Binary Path:

NxpExtns:   GetNxpStrValue: NXP Config Parameter : NXP_NFC_FW_NAME=��

NxpFwDnld:  Ignoring Config:NFC FW Binary :libpn548ad

NxpFwDnld:  NFC FW Binary :/libpn548ad_fw.so

NxpFwDnld:  @@@/libpn548ad_fw.so
NxpFwDnld:  NULL handler : unable to load the binary file, verify binary path
NxpFwDnld:  FW Image Length - ImageInfoLen 0
NxpFwDnld:  FW Image Info Pointer - pImageInfo 0
NxpFwDnld:  Image extraction Failed - invalid imginfo or imginfolen!!
NxpFwDnld:  Error loading libpn54x_fw !!

NxpHal:     FW version for FW file = 0x0
NxpHal:     FW version from device = 0x1001a0
NxpFwDnld:  Freeing Mem for Dnld Context..
NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpFunc:    NfcAdaptation::HalDeviceContextCallback: event=0
NxpFunc:    NfcAdaptation::HalWrite
NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   4 > 20000101
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   6 > 400003001101
NxpTml:     PN54X - Posting read message.....

NxpHal:     write successful status = 0x0
NxpHal:     read successful status = 0x0
NxpFunc:    NfcAdaptation::HalDeviceContextDataCallback: len=6
NxpFunc:    NfcAdaptation::HalWrite
NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   3 > 200100
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =  28 > 40011900031E030008000102038081828302D002FF020004881001A0
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     NxpNci> FW Version: 10.1.a0
NxpHal:     phNxpNciHal_deriveChipType HwVersion : 0x88
NxpHal:     phNxpNciHal_deriveChipType NxpNci > Product : PN548C2
NxpFunc:    NfcAdaptation::HalDeviceContextDataCallback: len=28
NxpFunc:    NfcAdaptation::HalCoreInitialized
NxpExtns:   find found NXP_ACT_PROP_EXTN=/

NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_ACT_PROP_EXTN

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   3 > 2F0200
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   8 > 4F02050000009F97
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpExtns:   find found NXP_SYS_CLK_SRC_SEL=(0x1)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXP_SYS_CLK_SRC_SEL=(0x1)

NxpExtns:   find found NXP_SYS_CLK_FREQ_SEL=

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXP_SYS_CLK_FREQ_SEL=(0x0)

NxpExtns:   find found NXP_SYS_CLOCK_TO_CFG=(0x1)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXP_SYS_CLOCK_TO_CFG=(0x1)

NxpFwDnld:  gphNxpNciHal_fw_IoctlCtx.bClkSrcVal = 0x1
NxpFwDnld:  gphNxpNciHal_fw_IoctlCtx.bClkFreqVal = 0x0
NxpFwDnld:  gphNxpNciHal_fw_IoctlCtx.bClkFreqVal = 0x1
NxpFwDnld:  Clock frequency value is wrong in config file, setting it as default
NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =  10 > 20030703A002A003A004
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =  17 > 40030E0003A0020101A0030108A0040101
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   8 > 20020501A0030108
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   5 > 4002020000
NxpTml:     PN54X - Posting read message.....

NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpHal:     phNxpNciHal_check_factory_reset file not present = /data/nfc/nfaStorage.bin1
NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =  26 > 20021702A0EA08FFFFFFFFFFFFFFFFA0EB08FFFFFFFFFFFFFFFF
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   5 > 4002020000
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpExtns:   find found NXP_NFC_PROFILE_EXTN= �D

NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_NFC_PROFILE_EXTN

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =   8 > 20020501A0440100
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   5 > 4002020000
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpHal:     Performing TVDD Settings
NxpExtns:   find found NXP_EXT_TVDD_CFG=(0x2)

NxpExtns:   GetNxpNumValue: NXP Config Parameter : NXP_EXT_TVDD_CFG=(0x2)

NxpExtns:   find found NXP_EXT_TVDD_CFG_2= �d

NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_EXT_TVDD_CFG_2

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =  10 > 20020701A00E03066400
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   5 > 4002020000
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpHal:     Performing RF Settings BLK 1
D���xtns:   find found NXP_RF_CONF_BLK_1= ��

NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_RF_CONF_BLK_1

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len = 166 > 2002A313A00D0604359001F401A00D06064401900300A00D060630B0011000A00D0606420200FFFFA00D03063F04A00D0620428800FFFFA00D0422442300A00D06222D50340C00A00D063242F800FFFFA00D06342D24370C00A00D06343386800070A00D0434442200A00D06422D15450D00A00D0446442200A00D06462D05590E00A00D0644428800FFFFA00D06562D059F0C00A00D0654428800FFFFA00D060A3380860070
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   5 > 4002020000
NxpTml:     PN54X - Posting read message.....

NxpHal:     write successful status = 0x0
NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpHal:     Performing RF Settings BLK 2
NxpExtns:   find found NXP_RF_CONF_BLK_2= �W3

NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_RF_CONF_BLK_2

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =  24 > 20021501A01D115733141700AA850080552A040063000000
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   5 > 4002020000
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_OK
NxpHal:     Response timer stopped
NxpHal:     Checking response
NxpHal:     Performing RF Settings BLK 3
NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_RF_CONF_BLK_3

NxpHal:     Performing RF Settings BLK 4
NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_RF_CONF_BLK_4

NxpHal:     Performing RF Settings BLK 5
NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_RF_CONF_BLK_5

NxpHal:     Performing RF Settings BLK 6
NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_RF_CONF_BLK_6

NxpHal:     Performing NAME_NXP_CORE_CONF_EXTN Settings
NxpExtns:   find found NXP_CORE_CONF_EXTN=      �^�@�A�C

NxpExtns:   GetNxpByteArrayValue: NXP Config Parameter : NXP_CORE_CONF_EXTN

NxpTml:     PN54X - Read requested.....

NxpTml:     PN54X - Invoking I2C Read.....

NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =  20 > 20020902A05E0101A0400101A0410104A0430100
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................

NxpHal:     write successful status = 0x0
NxpHal:     Response timer started
NxpHal:     Waiting after ext cmd sent
NxpTml:     PN54X - I2C Read successful.....

NxpNciR:     len =   4 > 40020105
NxpTml:     PN54X - Posting read message.....

NxpHal:     read successful status = 0x0
NxpHal:     phNxpNciHal_print_res_status: response status =STATUS_SYNTAX_ERROR
NxpHal:     Invalid Data from config file . Aborting..
NxpTml:     PN54X - Write requested.....

NxpTml:     PN54X - Invoking I2C Write.....

NxpNciX:     len =  10 > 21030703800181018201
NxpTml:     PN54X - I2C Write successful.....

NxpTml:     PN54X - Posting Fresh Write message.....

NxpTml:     PN54X - Tml Writer Thread Running................`

**Comment by ChevalierDeBalibari** [comment]
Still, no tag is detected.

**Comment by jgeslin** [comment]
You wrongly updated parameter NXP_CORE_CONF_EXTN parameter. Indeed, third byte relates to the complete frame size and fourth one to the number of parameter set in this command.
Here is the correct frame definition according to the configuration you seem to expect:
NXP_CORE_CONF_EXTN={20, 02, 11, 04,
    A0, 5E, 01, 01,
    A0, 40, 01, 00,
    A0, 41, 01, 04,
    A0, 43, 01, 00
}

**Comment by ChevalierDeBalibari** [comment]
thanks! it works now. sensitivity is not great but we will fix it up
