### ISSUE TITLE
README links to Page Not Found for Application Note AN11697

### ISSUE THREAD

**Issue by Peter-Krebs** [NXPNFCLinux/linux_libnfc-nci#126]
The [README.md](https://github.com/NXPNFCLinux/linux_libnfc-nci/blob/master/README.md) links for Application Note AN11697 no longer work and send users to a [Page Not Found](https://www.nxp.com/documents/application_note/AN11697.pdf) message.

All links to this document have to be replaced with the correct Application Note.

*Edit: grammar*

**Comment by jgeslin** [comment]
This is fixed now. Thanks for the hints.
