### ISSUE TITLE
NFC Desfire

### ISSUE THREAD

**Issue by Deepanraj123** [NXPNFCLinux/linux_libnfc-nci#19]
Hi ,

Am currently using this library for testing NFC using PN1720 .Am not able to read or write to my desfire card with this demo application.Is there any changes required to be done to read / write data from desfire card.

Thank you,
Deepanraj.A

**Comment by jgeslin** [comment]
Follow up of the discussion can be found here; [https://community.nxp.com/message/840107?commentID=840107&et=watches.email.thread#comment-840107](https://community.nxp.com/message/840107?commentID=840107&et=watches.email.thread#comment-840107)

Basically the linux_libnfc-nci doesn't provide reliable functionality of the MIFARE Cards NDEF formatting.
