### ISSUE TITLE
is it compatible with pn544 ?

### ISSUE THREAD

**Issue by AMV007** [NXPNFCLinux/linux_libnfc-nci#20]
Hello, I can't run it with pn544, any suggestions ?

**Comment by jgeslin** [comment]
Indeed, the linux libnfc-nci stack is only compatible with NXP NFC controllers implementing NCI interface. Information about NXP NFC Controller can be found on [NXP website](http://www.nxp.com/products/identification_and_security/nfc_and_reader_ics/nfc_controller_solutions/#overview).
For PN544, recommendation is to use [Linux NFC stack](https://01.org/linux-nfc).
