### ISSUE TITLE
force radio off ?

### ISSUE THREAD

**Issue by ContribOpenSource** [NXPNFCLinux/linux_libnfc-nci#23]
Hello,

How to be sure to disable radio, even if a tag is currently polled (something similar to rfkill in WiFi) ?
nfcManager_disableDiscovery() will do it ?

Thanks,
Contrib

**Comment by jgeslin** [comment]
Yes, I confirm calling nfcManager_disableDiscovery() API will stop the RF carrier even if a tag is currently connected.
