### ISSUE TITLE
Type 2 Tag with multiple TLV

### ISSUE THREAD

**Issue by ContribOpenSource** [NXPNFCLinux/linux_libnfc-nci#29]
Hello,

There are 2 kinds of memory structure in NFC Forum Type 2 Tag:
- static
- dynamic

In particular, for dynamic layout, first TLV may not be a "NDEF Message TLV" (= 0x03), and likely be a "Lock Control TLV" (= 0x01).

Q1) So how application (Tag Reader only) using lib R2.1 has to handle these cases (where first TLV is different than 0x03) ?

Q2) Is it entirely handled by library or application has to handle it too ?

Q3) Does nfcTag_isNdef() still return true in this case ?

Q4) More generally, what if they are multiple 0x03 TLV: how to iterate for each TLV ?

Thanks for your help,
Contrib

**Comment by jgeslin** [comment]
Hi,

Q1/Q2: libnfc-nci linux stack handles internally the different TLV types. This information is abstracted at the library API level.

Q3: nfcTag_isNdef() return true if CC as well as all TLV fields are coorect according T2T specification but also that tag contain a NDEF TLV even with null size.

Q4: Only the first (and mandatory as specified) NDEF TLV is considered by the libnfc-nci stack. Next ones are ignored.

Regards,
Jeremy.
