### ISSUE TITLE
Export Control ?

### ISSUE THREAD

**Issue by ContribOpenSource** [NXPNFCLinux/linux_libnfc-nci#35]
Hello,

Can you please provide information about Export Control ?

Regards,
Contrib

**Comment by jgeslin** [comment]
Hi, 
What information are you looking for ?
FYI, this software piece is delivered under Apache 2.0 licensing and is not subject to Export Control restrictions.

Regards,
Jeremy.

**Comment by ContribOpenSource** [comment]
Hello,

OK, but what is its ECCN ?
https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn

Thanks,
Contrib

**Comment by jgeslin** [comment]
Hi,

NXP's products (including SW) that are not under any export control regulations have no ECCN.

Regards,
Jeremy.

**Comment by ContribOpenSource** [comment]
OK, thanks for confirmation.

Regards,
Contrib
