### ISSUE TITLE
nfcDemoApp loading error

### ISSUE THREAD

**Issue by prattom** [NXPNFCLinux/linux_libnfc-nci#36]
I compiled the library for imx6ul evk board running yocto. But when I try to run the nfcDemoApp I received the following error
nfcDemoApp: error while loading shared libraries: /usr/lib/libnfc_nci_linux-1.so: internal error

**Comment by jgeslin** [comment]
Is the library .so file present inside /usr/lib ?
Did you set LD_LIBRARY_PATH accordingly ?

**Comment by prattom** [comment]
The error was due to the compiler I was using for library compilation.
