### ISSUE TITLE
Polling frequently freezes or stops working after a few scans

### ISSUE THREAD

**Issue by traic** [NXPNFCLinux/linux_libnfc-nci#5]
I'm experiencing an issue where polling might not working when starting up the demo app, or will freeze after a few scans (regardless whether it is scanning an Android HCE device or the MiFare smart card). I'm trying to isolate whether this is a hardware issue or software issue. Have you guy's experience this on a Raspberry Pi using the linux image that you provide?

**Comment by jgeslin** [comment]
I never seen such behavior on the used platforms (Raspberyy Pi, beagle bone, and a couple of others).
You can easily activate traces for debug at runtime by setting NXPLOG_XXX_LOGLEVEL parameters to value 0x03 inside /etc/libnfc-nxp.conf file on the target.

**Comment by traic** [comment]
ok will give that a try, maybe it's a power supply issue, or faulty reader.

**Comment by jgeslin** [comment]
Any update on the issue ? Can we close it ?

**Comment by jgeslin** [comment]
Closed because of no further feedback about this issue.
