### ISSUE TITLE
Timing analysis

### ISSUE THREAD

**Issue by prattom** [NXPNFCLinux/linux_libnfc-nci#67]
Is it possible to do timing analysis for time taken to detect tag? Is there option for this in library currently?

**Comment by jgeslin** [comment]
Recent commit https://github.com/NXPNFCLinux/linux_libnfc-nci/commit/44873c5c75150afecc7122f60ffebebbcb59a745 added timestamp to the debug traces (those traces being enabled thanks to NXPLOG_xxx_LOGLEVEL parameter inside libnfc-nxp.conf file).
This should allow analyzing timings.
