### ISSUE TITLE
how to display all detected cards and iterate through them

### ISSUE THREAD

**Issue by l-spitz** [NXPNFCLinux/linux_libnfc-nci#71]
I understand anti-collision is implemented so that only the first tag detected is reported.  I would like to see all tags found, and perhaps select and read each one in order.

Is that possible in this library, and if so where do I start?

**Comment by jgeslin** [comment]
Indeed, the library API doesn't offer possibility to select another tag when several were detected.
We may consider this update in next release of the SW stack.

**Comment by l-spitz** [comment]
Thanks, found in NfcTag.h a couple of f methods that seem to provide what I need 
selectFirstTag() and selectNextTag()
