### ISSUE TITLE
NFCDemoApp not working with i.MX6 Board

### ISSUE THREAD

**Issue by md-jamal** [NXPNFCLinux/linux_libnfc-nci#77]
Hi Guys,

I have a customized i.MX6 Board , I first tested PN7120 on Raspberry Pi and it worked out of the box.

When I switched to my i.MX6 Board, it is not working.

Here are my changes:

1. Device Tree:

pn547: pn547@28 {
                compatible = "nxp,pn547";
                reg=<0x28>;
                clock-frequency = <400000>;
                interrupt-gpios = <&gpio3 19 0>;
                enable-gpios = <&gpio2 30 0>;

        };
2. Added pn5xx_i2c driver as a Module and when loading the module here are the logs and it created /dev/pn544

pn54x_dev_init
pn54x_probe
pn544 1-0028: FIRM GPIO <OPTIONAL> error getting from OF node
pn544 1-0028: CLKREQ GPIO <OPTIONAL> error getting from OF node
pn54x_get_pdata: could not get nxp,pn54x-pvdd, rc=-19
pn54x_get_pdata: could not get nxp,pn54x-vbat, rc=-19
pn54x_get_pdata: could not get nxp,pn54x-pmuvcc, rc=-19
pn54x_get_pdata: could not get nxp,pn54x-sevdd, rc=-19
pn54x_probe: request irq_gpio 83
pn54x_probe: request ven_gpio 62
pn54x_probe : requesting IRQ 243

3. When I executed ./nfcDemoApp poll, it failed with the following logs.

#########################################################################################
##    pn54x_dev_open : 10,58
                                 pn54x_dev_ioctl, cmd=1074063617, arg=1
  NFC demo                       pn544_enable power on
               ##
#########################################################################################
#########################################################################################
                              ... press enter to quit ...

1523001242:920:847 - NxpExtns:   find found NXPLOG_TML_LOGLEVEL=(0x3)

1523001242:920:946 - NxpExtns:   find found NXPLOG_FWDNLD_LOGLEVEL=(0x3)

1523001242:920:986 - NxpExtns:   find found NXPLOG_NCIX_LOGLEVEL=(0x3)

1523001242:921:024 - NxpExtns:   find found NXPLOG_NCIR_LOGLEVEL=(0x3)

0:000:211 - NxpHal:     Entering phNxpNciHal_init_monitor
0:000:268 - NxpHal:     Returning with SUCCESS
0:000:332 - NxpTml:     phTmlNfc_i2c_open_and_configure

0:000:382 - NxpTml:     Opening port=/dev/pn544

0:002:874 - NxpTml:     phTmlNfc_i2c_reset(), VEN level 1
0:217:033 - pn54x_dev_ioctl, cmd=1074063617, arg=0
NxpTml:     phTmlNfc_i2c_reset(),pn544_disable power off
 VEN level 0
0:427:036 - pn54x_dev_ioctl, cmd=1074063617, arg=1
NxpTml:     phTmlNfc_i2c_reset(),pn544_enable power on
 VEN level 1
0:537:093 - pn54x_dev_write : i2c_master_send returned -5
NxpTml:     PN54X - Tml Reader Thpn54x_dev_write : i2c_master_send returned -5
read Started................

0pn54x_dev_write : i2c_master_send returned -5
:537:169 - NxpTml:     PN54X - Tml Writer Thread Started.........pn54x_dev_write : i2c_master_send returned -5
.......

0:537:279 - NxpTml:     PN54X - Tml Writer Thread Runnpn54x_dev_write : i2c_master_send returned -5
ing................

0:537:312 pn54x_dev_write : i2c_master_send returned -5
- NxpHal:     0:537:325 - 0:537:3pn54x_dev_ioctl, cmd=1074063617, arg=1
84 - NxpTml:     NxpTml:     PN54pn544_enable power on
X - Write requested.....
thread started

0:537:481 - NxpTml:     PN54X - Invoking I2C Write.....

PN54X - Read requested.....

0:537:559 - NxpTml:     PN54X - Invoking I2C Read.....

0:543:267 - NxpTml:     _i2c_write() errno : 5
0:543:313 - NxpTml:     PN54X - Error in I2C Write.....

0:543:346 - NxpTml:     PN54X - Posting Fresh Write message.....

0:543:445 - NxpTml:     PN54X - Tml Writer Thread Running................

0:543:470 - NxpHal:     write error status = 0x1ff
0:543:562 - NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
0:544:643 - NxpTml:     PN54X - Write requested.....

0:544:683 - NxpTml:     PN54X - Invoking I2C Write.....

0:550:242 - NxpTml:     _i2c_write() errno : 5
0:550:284 - NxpTml:     PN54X - Error in I2C Write.....

0:550:317 - NxpTml:     PN54X - Posting Fresh Write message.....

0:550:356 - NxpTml:     PN54X - Tml Writer Thread Running................

0:550:376 - NxpHal:     write error status = 0x1ff
0:550:468 - NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
0:551:547 - NxpTml:     PN54X - Write requested.....

0:551:588 - NxpTml:     PN54X - Invoking I2C Write.....

0:557:230 - NxpTml:     _i2c_write() errno : 5
0:557:273 - NxpTml:     PN54X - Error in I2C Write.....

0:557:307 - NxpTml:     PN54X - Posting Fresh Write message.....

0:557:350 - NxpTml:     PN54X - Tml Writer Thread Running................

0:557:366 - NxpHal:     write error status = 0x1ff
0:557:495 - NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
0:558:575 - NxpTml:     PN54X - Write requested.....

0:558:617 - NxpTml:     PN54X - Invoking I2C Write.....

0:567:253 - NxpTml:     _i2c_write() errno : 5
0:567:303 - NxpTml:     PN54X - Error in I2C Write.....

0:567:336 - NxpTml:     PN54X - Posting Fresh Write message.....

0:567:375 - NxpTml:     PN54X - Tml Writer Thread Running................

0:567:407 - NxpHal:     write error status = 0x1ff
0:567:592 - NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
0:568:680 - NxpTml:     PN54X - Write requested.....

0:568:735 - NxpTml:     PN54X - Invoking I2C Write.....

0:576:641 - NxpTml:     _i2c_write() errno : 5
0:576:674 - NxpTml:     PN54X - Error in I2C Write.....

0:576:702 - NxpTml:     PN54X - Posting Fresh Write mepn54x_dev_ioctl, cmd=1074063617, arg=0
ssage.....

0:576:734 - NxpTml:pn544_disable power off
     PN54X - Tml Writer Thread Rupn54x_dev_read: i2c_master_recv returned -5
nning................

0:576:74pn54x_dev_read: i2c_master_recv returned -5
8 - NxpHal:     write error statupn54x_dev_read: i2c_master_recv returned -5
s = 0x1ff
0:576:820 - NxpHal:   pn54x_dev_read: i2c_master_recv returned -5
  write_unlocked failed - PN54X Mpn54x_dev_read: i2c_master_recv returned -5
aybe in Standby Mode - Retry
0:5pn54x_dev_read: i2c_master_recv returned -5
77:893 - NxpTml:     PN54X - Writpn54x_dev_read: i2c_master_recv returned -5
e requested.....

0:577:930 - Npn54x_dev_read: i2c_master_recv returned -5
xpTml:     PN54X - Invoking I2C Wpn54x_dev_read: i2c_master_recv returned -5
rite.....

0:583:597 - NxpTml: pn54x_dev_read: i2c_master_recv returned -5
    _i2c_write() errno : 5
0:583pn54x_dev_read: i2c_master_recv returned -5
:630 - NxpTml:     PN54X - Error pn54x_dev_read: i2c_master_recv returned -5
in I2C Write.....

0:583:657 - pn54x_dev_read: i2c_master_recv returned -5
NxpTml:     PN54X - Posting Freshpn54x_dev_read: i2c_master_recv returned -5
 Write message.....

0:583:688 pn54x_dev_read: i2c_master_recv returned -5
- NxpTml:     PN54X - Tml Writer pn54x_dev_read: i2c_master_recv returned -5
Thread Running................
pn54x_dev_read: i2c_master_recv returned -5

0:583:702 - NxpHal:     write erpn54x_dev_read: i2c_master_recv returned -5
ror status = 0x1ff
0:583:775 - NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode (max count = 0x6)
0:583:816 - NxpTml:     phTmlNfc_i2c_reset(), VEN level 1
0:797:021 - NxpTml:     phTmlNfc_i2c_reset(), VEN level 0
0:814:813 - NxpTml:     _i2c_read() [hdr] errno : 5
0:814:873 - NxpTml:     PN54X - Error in I2C Read.....

0:814:907 - NxpTml:     PN54X - Read requested.....

0:814:938 - NxpTml:     PN54X - Invoking I2C Read.....

0:821:625 - NxpTml:     _i2c_read() [hdr] errno : 5
0:821:672 - NxpTml:     PN54X - Error in I2C Read.....

0:821:707 - NxpTml:     PN54X - Read requested.....

0:821:741 - NxpTml:     PN54X - Invoking I2C Read.....

0:828:432 - NxpTml:     _i2c_read() [hdr] errno : 5
0:828:468 - NxpTml:     PN54X - Error in I2C Read.....

0:828:495 - NxpTml:     PN54X - Read requested.....

0:828:521 - NxpTml:     PN54X - Invoking I2C Read.....

0:835:160 - NxpTml:     _i2c_read() [hdr] errno : 5
0:835:213 - NxpTml:     PN54X - Error in I2C Read.....

0:835:240 - NxpTml:     PN54X - Read requested.....

0:835:266 - NxpTml:     PN54X - Invoking I2C Read.....

0:841:966 - NxpTml:     _i2c_read() [hdr] errno : 5
0:842:002 - NxpTml:     PN54X - Error in I2C Read.....

0:842:032 - NxpTml:     PN54X - Read requested.....

0:842:060 - NxpTml:     PN54X - Invoking I2C Read.....

0:848:743 - NxpTml:     _i2c_read() [hdr] errno : 5
0:848:781 - NxpTml:     PN54X - Error in I2C Read.....

0:848:809 - NxpTml:     PN54X - Read requested.....

0:848:836 - NxpTml:     PN54X - Invoking I2C Read.....

0:855:511 - NxpTml:     _i2c_read() [hdr] errno : 5
0:855:562 - NxpTml:     PN54X - Error in I2C Read.....

0:855:589 - NxpTml:     PN54X - Read requested.....

0:855:615 - NxpTml:     PN54X - Invoking I2C Read.....

0:862:345 - NxpTml:     _i2c_read() [hdr] errno : 5
0:862:384 - NxpTml:     PN54X - Error in I2C Read.....

0:862:412 - NxpTml:     PN54X - Read requested.....

0:862:438 - NxpTml:     PN54X - Invoking I2C Read.....

0:869:096 - NxpTml:     _i2c_read() [hdr] errno : 5
0:869:133 - NxpTml:     PN54X - Error in I2C Read.....

0:869:161 - NxpTml:     PN54X - Read requested.....

0:869:188 - NxpTml:     PN54X - Invoking I2C Read.....

0:875:861 - NxpTml:     _i2c_read() [hdr] errno : 5
0:875:912 - NxpTml:     PN54X - Error in I2C Read.....

0:875:939 - NxpTml:     PN54X - Read requested.....

0:875:965 - NxpTml:     PN54X - Invoking I2C Read.....

0:882:645 - NxpTml:     _i2c_read() [hdr] errno : 5
0:882:696 - NxpTml:     PN54X - Error in I2C Read.....

0:882:723 - NxpTml:     PN54X - Read requested.....

0:882:748 - NxpTml:     PN54X - Invoking I2C Read.....

0:889:445 - NxpTml:     _i2c_read() [hdr] errno : 5
0:889:482 - NxpTml:     PN54X - Error in I2C Read.....

0:889:511 - NxpTml:     PN54X - Read requested.....

0:889:538 - NxpTml:     PN54X - Invoking I2C Read.....

0:896:212 - NxpTml:     _i2c_read() [hdr] errno : 5
0:896:262 - NxpTml:     PN54X - Error in I2C Read.....

0:896:289 - NxpTml:     PN54X - Read requested.....

0:896:314 - NxpTml:     PN54X - Invoking I2C Read.....

0:902:995 - NxpTml:     _i2c_read() [hdr] errno : 5
0:903:047 - NxpTml:     PN54X - Error in I2C Read.....

0:903:074 - NxpTml:     PN54X - Read requested.....

0:903:100 - NxpTml:     PN54X - Invoking I2C Read.....

0:909:853 - NxpTml:     _i2c_read() [hdr] errno : 5
0:909:892 - NxpTml:     PN54X - Error in I2C Read.....

0:909:920 - NxpTml:     PN54X - Read requested.....

0:909:946 - NxpTml:     PN54X - Invoking I2C Read.....

0:916:562 - NxpTml:     _i2c_read() [hdr] errno : 5
0:916:613 - NxpTml:     PN54X - Error in I2C Read.....

0:916:639 - NxpTml:     PN54X - Read requested.....

0:916:664 - NxpTml:     PN54X - Invoking I2C Read.....

0:923:346 - NxpTml:     _i2c_read() [hdr] errno : 5
0:9pn54x_dev_ioctl, cmd=1074063617, arg=1
23:396 - NxpTml:     PN54X - Erropn544_enable power on
r in I2C Read.....

0:923:423 - NxpTml:     PN54X - Read requested.....

0:923:448 - NxpTml:     PN54X - Invoking I2C Read.....

0:930:143 - NxpTml:     _i2c_read() [hdr] errno : 5
0:930:182 - NxpTml:     PN54X - Error in I2C Read.....

1:017:016 - NxpTml:     phTmlNfc_i2c_reset(), VEN level 1
1:263:552 - NxpTml:     PN54X - Read requested.....

1:274:747 - NxpTml:     PN54X - Invoking I2C Read.....

1:376:993 - NxpHal:     PN54X Reset - SUCCESS

1:377:091 - NxpHal:     phNxpNciHal_write failed for hal ext
1:377:122 - NxpHal:     Force FW Download, NFCC not coming out from Standby

I have seen a similar issue in github, what is the next step for me to resolve this issue.

**Comment by md-jamal** [comment]
I also tried switching to Alt Mode and after enabling logs it is printing these in loop

13:746:530 - NxpTml:     PN54X - Error in I2C Read.....

13:746:557 - NxpTml:     PN54X - Read requested.....

13:746:593 - NxpTml:     PN54X - Invoking I2C Read.....

13:746:625 - NxpTml:     Error with interrupt-detect pin (0)
13:746:905 - NxpTml:     _i2c_read() [hdr] errno : 5
13:746:939 - NxpTml:     PN54X - Error in I2C Read.....

**Comment by jgeslin** [comment]
The first thing to check is the level of PN7150 VEN signal (HW reset function). It should be driven high to allow proper PN7150 function. If not going high during linux libnfc-nci library initialization (when starting the demo application) it probably mean the DTS definition does not match the physical connection.

While using the Alternative to kernel driver solution (alt mode), you must insure the gpios are not already used. This is probably the case if the pn5xx_i2c driver is loaded. So before lanuching the demo app (with libnfc-nci library configured in alt mode), unload the pn5xx_i2c  driver.

**Comment by md-jamal** [comment]
What do you mean by driving high in Driver Mode.. Are there any cons of using alt mode..

**Comment by jgeslin** [comment]
VEN must be driven high to make PN7150 active (a low pulse triggers PN7150 reset) independently of the mode used (kernel driver or alt). This is managed by the libnfc-nci stack through the /dev/pn544 (in case of pn5xx_i2c driver use) or through /sys/class/gpio (in case of alt mode).

**Comment by md-jamal** [comment]
You mean in the device tree, we need to set the default value to 1.

**Comment by jgeslin** [comment]
> You mean in the device tree, we need to set the default value to 1.

No, the libnfc-nci linux is usually managing the GPIO via the pn5xx_i2c driver.
What I meant is that you should check the signal level of VEN. If it is not high it point to an issue with the driver or rather about the DTS definition.

**Comment by jgeslin** [comment]
Closed because considered answered and no comment since 1 year.
