### ISSUE TITLE
Unable to get NDEF from HCE peer if not separating two OM5578/PN7150RPI and put them back

### ISSUE THREAD

**Issue by orange-kao** [NXPNFCLinux/linux_libnfc-nci#79]
## Reproduce steps
1. Get two pieces of Raspberry Pi (unit A and B), and install OM5578/PN7150RPI on it.
2. Put two pieces of OM5578/PN7150RPI facing each other (less than 1cm between two antenna)
3. Run "nfcDemoApp poll" on unit A
3. Run "nfcDemoApp share --type=mime -m xyz/123 -d 6162636465" on unit B

## Expected result
Unit A detect unit B and read NDEF from it.

Unit A should print

```
	NFC Tag Found

        Type :         'Type A'
        NFCID1 :    	'01 02 03 04 '
		Record Found :
				NDEF Content Max size :     '253 bytes'
				NDEF Actual Content size :     '15 bytes'
				ReadOnly :                         'TRUE'

		TNF Media

			Type : xyz/123
			Data : abcde

		15 bytes of NDEF data received :
		D2 07 05 78 79 7A 2F 31 32 33 61 62 63 64 65 
```

## Actual result
Unit A print the following message repeatedly

```
Waiting for a Tag/Device...

	Device Found
	Device Lost

Waiting for a Tag/Device...

	Device Found
	Device Lost

Waiting for a Tag/Device...
```

Unit B print
`
Waiting for a Tag/Device...
`

It seems that unit A is able detected the peer over the air, but not able to receive NDEF from unit B.
Reproducibility 70%.

## Additional information
Manually separate unit A and B, and put them together again (without terminating nfcDemoApp), may enable unit A to read from unit B and print NDEF message correctly.

Switching step 3 with step 4 will make the issue unreproducable. (but why?)

libnfc-nci was built with
```
./bootstrap
openssldir=/usr ./configure --prefix=/usr --enable-pn7150 --enable-alt --enable-llcp1_3
make
```

If the debug message has been enabled, unit A will kept printing I2C read/write message but not NDEF. Sample as below.

```
119:963:296 - NxpTml:     PN54X - Invoking I2C Read.....

119:963:300 - NxpTml:     PN54X - Write requested.....

119:963:494 - NxpTml:     PN54X - Invoking I2C Write.....

119:964:472 - NxpNciX:     len =   5 > 0000020000
119:964:516 - NxpTml:     PN54X - I2C Write successful.....

119:964:547 - NxpTml:     PN54X - Posting Fresh Write message.....

119:964:586 - NxpTml:     PN54X - Tml Writer Thread Running................

119:964:600 - NxpHal:     write successful status = 0x0
119:966:223 - NxpTml:     PN54X - I2C Read successful.....

119:966:337 - NxpNciR:     len =   6 > 600603010001
119:966:396 - NxpTml:     PN54X - Posting read message.....

119:966:457 - NxpHal:     read successful status = 0x0
119:966:530 - NxpTml:     PN54X - Read requested.....

119:966:575 - NxpTml:     PN54X - Invoking I2C Read.....

119:982:968 - NxpTml:     PN54X - I2C Read successful.....

119:983:030 - NxpNciR:     len =   5 > 0000020000
119:983:071 - NxpTml:     PN54X - Posting read message.....

119:983:131 - NxpHal:     read successful status = 0x0
119:983:205 - NxpTml:     PN54X - Read requested.....

119:983:307 - NxpTml:     PN54X - Invoking I2C Read.....

119:983:218 - NxpExtns:   find found MIFARE_READER_ENABLE=(0x1)

119:983:429 - NxpTml:     PN54X - Write requested.....

119:983:492 - NxpTml:     PN54X - Invoking I2C Write.....

119:984:517 - NxpNciX:     len =   5 > 0000020000
119:984:572 - NxpTml:     PN54X - I2C Write successful.....

119:984:616 - NxpTml:     PN54X - Posting Fresh Write message.....

119:984:662 - NxpTml:     119:984:676 - NxpHal:     write successful status = 0x0
PN54X - Tml Writer Thread Running................

119:986:204 - NxpTml:     PN54X - I2C Read successful.....

119:986:260 - NxpNciR:     len =   6 > 600603010001
119:986:293 - NxpTml:     PN54X - Posting read message.....
```

Thank you.

**Comment by jgeslin** [comment]
Hi,

Indeed, the "share" mode of the demo application (see main.c, "cmd_share" function) enable P2P ("Init_env" function call) before configuring the SNEP server ("WaitDeviceArrival" call) allowing to share the NDEF message. This way, if the P2P communication is established in-between, device A cannot retrieve the NDEF message from devie B until P2P communication is re-established.
You may reduce this "time frame" using attached patch.
[patch_shareNDEF.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/2000059/patch_shareNDEF.txt)


Regards,
Jeremy.
