### ISSUE TITLE
Detection of tag model

### ISSUE THREAD

**Issue by kazbeel** [NXPNFCLinux/linux_libnfc-nci#81]
I am wondering if there is a way to detect the model of tag. In another application (which uses NxpNfcRDLib) I am doing this by checking the `SAK` and the `ATQ` as the document [AN10833](https://www.nxp.com/docs/en/application-note/AN10833.pdf) specifies. But, how this could be done in this situation?

**Comment by jgeslin** [comment]
Hi,

The library does not expose ATQA and SAK information. However it parse it to distinguish the supported protocol (MIFARE Ultralight, MIFARE Classic or ISO14443-4).

Regards,
Jeremy.

**Comment by jgeslin** [comment]
Closed because considered answered and no comment since 1 year.
