### ISSUE TITLE
Build failure on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by muddog** [NXPNFCLinux/linux_libnfc-nci#87]
Hi 

Looks like the libtool 2.4.6 version has problem to build the libnfc_nci_linux.so. Need to hard code the arm-libtool script to enable the share library build, correct the $lib variable in the $archive_cmds and hardcode the libnfc_nci_linux.la for the $library_names to build the .so.

**Comment by jgeslin** [comment]
From my side on Ubuntu 16.04.1 and libtool 2.4.6 on x86 machine I don't see any issue.
Can you maybe share error logs ?

**Comment by jgeslin** [comment]
Closed because no feedback from almost 5 months.
